// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLEdn0Yf43flZCUx7pHYSiXBjzQwU-UeQ',
    appId: '1:245882539120:android:212010db36585d70c4f8b5',
    messagingSenderId: '245882539120',
    projectId: 'zoom-clone-7ce20',
    storageBucket: 'zoom-clone-7ce20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALeO8rNa7MtYaRlIeBLF3rC-WzNnXMAyc',
    appId: '1:245882539120:ios:77dc78f492d76d54c4f8b5',
    messagingSenderId: '245882539120',
    projectId: 'zoom-clone-7ce20',
    storageBucket: 'zoom-clone-7ce20.appspot.com',
    androidClientId: '245882539120-8fbo9l6stm28r6htmgtkfte37ko90n3m.apps.googleusercontent.com',
    iosClientId: '245882539120-kf1fs5995pcumh2i1nip9s6q4vbmku46.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
